import type { DiscoveryProvider } from '../provider-registry';
import type {
  DiscoveryCategory,
  DiscoveryItem,
  DiscoveryItemDetail,
} from '../types';

/**
 * GeminiEnrichmentProvider — generates AI-flavored recommendations.
 * Stub: returns mock AI summaries and recommendation items.
 * TODO: integrate with existing /api/hello 3-tier intelligence.
 */
export class GeminiEnrichmentProvider implements DiscoveryProvider {
  name = 'gemini';
  priority = 1;
  supports: DiscoveryCategory[] = [
    'restaurants',
    'hotels',
    'activities',
    'destinations',
    'day_plans',
    'experiences',
  ];

  async search(params: {
    query?: string;
    category?: DiscoveryCategory;
    location?: string;
    limit: number;
  }): Promise<DiscoveryItem[]> {
    const now = new Date().toISOString();
    const category = params.category ?? 'activities';
    const location = params.location ?? 'your area';
    const query = params.query ?? 'popular';

    const recommendations: DiscoveryItem[] = [
      {
        id: `gemini-rec-${Date.now()}-1`,
        title: `AI Pick: Best ${category} for "${query}"`,
        subtitle: `Curated by hello intelligence`,
        category,
        description: `Based on current trends and local insights, this is a top recommendation for ${query} in ${location}. Our AI analyzed hundreds of reviews and local signals to surface this pick.`,
        price: undefined,
        location,
        metadata: { aiGenerated: true, confidence: 0.87 },
        tasteScore: 88,
        tasteReason: `AI-matched to "${query}" intent`,
        source: 'gemini',
        fetchedAt: now,
      },
      {
        id: `gemini-rec-${Date.now()}-2`,
        title: `Hidden Gem: ${category} in ${location}`,
        subtitle: 'Off the beaten path',
        category,
        description: `A lesser-known ${category} option that consistently delights visitors who find it. Low tourist density, high local approval.`,
        price: undefined,
        location,
        metadata: { aiGenerated: true, confidence: 0.82 },
        tasteScore: 85,
        tasteReason: 'High local signal, low tourist noise',
        source: 'gemini',
        fetchedAt: now,
      },
      {
        id: `gemini-rec-${Date.now()}-3`,
        title: `Trending: ${category} experience`,
        subtitle: `Popular this season in ${location}`,
        category,
        description: `This ${category} option is seeing a surge in positive sentiment this season. Great for groups looking for a shared experience.`,
        price: undefined,
        location,
        metadata: { aiGenerated: true, confidence: 0.79 },
        tasteScore: 82,
        tasteReason: 'Strong seasonal momentum',
        source: 'gemini',
        fetchedAt: now,
      },
    ];

    return recommendations.slice(0, Math.min(params.limit, 5));
  }

  async getDetail(externalId: string): Promise<DiscoveryItemDetail | null> {
    if (!externalId.startsWith('gemini-')) return null;

    return {
      id: externalId,
      title: 'AI-Generated Recommendation',
      category: 'activities',
      description: 'An AI-curated recommendation based on group preferences and local trends.',
      metadata: { aiGenerated: true },
      tasteScore: 85,
      source: 'gemini',
      fetchedAt: new Date().toISOString(),
      longDescription:
        'This recommendation was generated by analyzing local trends, review sentiment, and group preference signals. The AI considers seasonality, crowd levels, and value-for-money when surfacing picks.',
      imageUrls: [],
      tags: ['ai-curated', 'trending'],
      aiSummary:
        'this spot keeps coming up in local conversations. solid choice for groups, especially if you want something authentic without the planning overhead.',
    };
  }

  async healthCheck(): Promise<{ status: 'ok' | 'degraded' | 'down' }> {
    // TODO: ping Gemini API health endpoint
    return { status: 'ok' };
  }
}
